# 스프링 부트 서버가 실행되면 자동으로 로딩되는 파일
# 데이터베이스의 설정 정보, 도깅 설정 정보 등이 들어갈 수 있고, 직접 설정을 정의할 때 사용
server:
  port: 80

spring:
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    url: jdbc:h2:mem:testdb # 메모리 H2 DB 경로 설정
  jpa:
    #전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create

    # 테이블 생성 후에 data.bak 실행
    defer-datasource-initialization: true